### ISSUE TITLE
Qualys® SSL Labs overall rating is a “B”

### ISSUE THREAD

**Issue by trdarr** [NickCarneiro/homepage#1]
https://www.ssllabs.com/ssltest/analyze.html?d=trillworks.com

I’m not sure what rating [Mozilla’s “intermediate” SSL configuration](https://mozilla.github.io/server-side-tls/ssl-config-generator/?server=nginx-1.1.9&openssl=1.0.2f&hsts=yes&profile=intermediate) will give you (with [custom 2048-bit Diffie-Hellman parameters](https://weakdh.org/sysadmin.html)), but it’s probably better than a “B” and gives you better compatibility anyway: neither configuration supports IE 6 or Java 6, but this one will support Android 2.3, IE 8, or Java 7 or 8.

**Comment by NickCarneiro** [comment]
fixed

![ssl](https://cloud.githubusercontent.com/assets/700209/12722096/1fdab826-c8b8-11e5-9535-35a531e27456.png)

**Comment by trdarr** [comment]
Nice! A couple of things:

* I think you need [HSTS](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) for an “A+” (`add_header Strict-Transport-Security`).
* “Session resumption (caching)” is orange. Check your [`ssl_session_cache`](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_session_cache)?
* If you upgrade to nginx 1.3.7, turn on [OCSP stapling](https://en.wikipedia.org/wiki/OCSP_stapling) ([`ssl_stapling` and friends](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_stapling)).
